### ISSUE TITLE
tke-monitor-api always crash in v1.8.0 

### ISSUE THREAD

**Issue by leoryu** [tkestack/tke#1630]
**What happened**:

==> Version:
  gitVersion: v1.8.0                                  
   gitCommit: 01ff9b7ef136f8ab2c943c0ae10809517e57ae46
gitTreeState: dirty                                   
   buildDate: 2021-09-28T07:23:21Z                    
   goVersion: go1.13.5                                
    compiler: gc                                      
    platform: linux/amd64                             
==> Log data will now stream in as it occurs:
2021-10-21 09:21:03.046	INFO	External CA file was not specified, using server certificate file: /app/certs/server.crt
2021-10-21 09:21:03.046	INFO	Initializing cache sizes based on 100MB limit
2021-10-21 09:21:08.756	INFO	Starting Tencent Kubernetes Engine Monitor API server
2021-10-21 09:21:08.759	INFO	Register monitor web service
I1021 09:21:08.759979       1 client.go:360] parsed scheme: "endpoint"
I1021 09:21:08.760008       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://etcd.kube-system:2379  <nil> 0 <nil>}]
I1021 09:21:08.947505       1 client.go:360] parsed scheme: "endpoint"
I1021 09:21:08.947535       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://etcd.kube-system:2379  <nil> 0 <nil>}]
I1021 09:21:09.047796       1 client.go:360] parsed scheme: "endpoint"
I1021 09:21:09.047824       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://etcd.kube-system:2379  <nil> 0 <nil>}]
2021-10-21 09:21:09.054	INFO	Enabling API group "monitor.tkestack.io".
2021-10-21 09:21:09.347	INFO	All of http handlers registered	{"paths": ["/apis", "/apis/monitor.tkestack.io", "/apis/monitor.tkestack.io/v1", "/apis/v1/monitor", "/metrics", "/version"]}
I1021 09:21:09.655145       1 client.go:360] parsed scheme: "endpoint"
I1021 09:21:09.655180       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://etcd.kube-system:2379  <nil> 0 <nil>}]
I1021 09:21:09.951806       1 secure_serving.go:197] Serving securely on [::]:9455
I1021 09:21:09.951853       1 dynamic_cafile_content.go:167] Starting request-header::/app/certs/front-proxy-ca.crt
I1021 09:21:09.951881       1 dynamic_serving_content.go:130] Starting serving-cert::/app/certs/server.crt::/app/certs/server.key
I1021 09:21:09.951906       1 tlsconfig.go:240] Starting DynamicServingCertificateController
2021-10-21 09:21:09.954	INFO	outer lock in getCluster
I1021 09:21:09.954915       1 dynamic_cafile_content.go:167] Starting client-ca-bundle::/app/certs/ca.crt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x22030d5]

goroutine 420 [running]:
tkestack.io/tke/pkg/monitor/util/cache.(*cacher).getTApps(0xc0005b7570, 0x2c75b80, 0xc000056018, 0xc000fd6420, 0xc000995a20, 0xc, 0x0)
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:355 +0x75
tkestack.io/tke/pkg/monitor/util/cache.(*cacher).getWorkloadCounter(0xc0005b7570, 0x2c75b80, 0xc000056018, 0xc000fd6420, 0xc000995a20, 0xc, 0xc00060cc60, 0x0)
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:689 +0x194
tkestack.io/tke/pkg/monitor/util/cache.(*cacher).getClusters.func1(0xc000995e50, 0xc000995e0c, 0x2, 0xc0546a2189406154, 0x1e9253303, 0x40fa880, 0xc0016a2e10, 0x2c75b80, 0xc000056018, 0xc0005b7570, ...)
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:179 +0x710
created by tkestack.io/tke/pkg/monitor/util/cache.(*cacher).getClusters
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:155 +0x314

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
E1125 09:01:07.936607       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 93 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x271c0c0, 0x406aed0)
	/home/ubuntu/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x271c0c0, 0x406aed0)
	/data/go/src/runtime/panic.go:965 +0x1b9
tkestack.io/tke/pkg/monitor/util/cache.(*cacher).getDynamicClients(0xc000498380, 0x2e43668, 0xc0001a0000, 0x0, 0x0, 0x0)
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:713 +0x69b
tkestack.io/tke/pkg/monitor/util/cache.(*cacher).getClusters(0xc000498380, 0x2e43668, 0xc0001a0000)
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:139 +0x8c
tkestack.io/tke/pkg/monitor/util/cache.(*cacher).Reload(0xc000498380)
	/data/actions-runner/_work/tke/tke/pkg/monitor/util/cache/cache.go:114 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005be078)
	/home/ubuntu/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005be078, 0x2df1800, 0xc000b605a0, 0xc0008ac701, 0xc0001a33e0)
	/home/ubuntu/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005be078, 0x8bb2c97000, 0x0, 0x1, 0xc0001a33e0)
	/home/ubuntu/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005be078, 0x8bb2c97000, 0xc0001a33e0)
	/home/ubuntu/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90 +0x4d
created by tkestack.io/tke/pkg/monitor/apiserver.completedConfig.postStartHookFunc.func1
	/data/actions-runner/_work/tke/tke/pkg/monitor/apiserver/apiserver.go:135 +0xa5
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x244fe5b]

**Comment by leoryu** [comment]
workaround is reboot node.
